name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: install ubuntu core 
      run: |
        sudo apt-get update
        sudo apt install git --fix-missing -y
        sudo apt install vim -y
        sudo apt-get install libpcap-dev -y
    - name: Install dependencies
      run: |
        sudo python -m pip install --upgrade pip
    - name: install shuize
      run: |
        git clone https://github.com/lisa-hue/ShuiZe_0x727.git
        cd ./ShuiZe_0x727
        sudo chmod 777 docker_build.sh
        sudo ./docker_build.sh
        
        sed -i 's/fofaemail/${{ secrets.FOFAEMAIL }}/g' ./iniFile/config.ini
        sed -i 's/fofakey/${{ secrets.FOFAKEY }}/g' ./iniFile/config.ini
        sed -i 's/shodankey/${{ secrets.SHODANKEY }}/g' ./iniFile/config.ini
        sed -i 's/githubapi/${{ secrets.GITHUBAPI }}/g' ./iniFile/config.ini
        sed -i 's/virustotalapi/${{ secrets.VIRUSTOTALAPI }}/g' ./iniFile/config.ini
        sed -i 's/censysuid/${{ secrets.CENSYSUID }}/g' ./iniFile/config.ini
        sed -i 's/censyssecret/${{ secrets.CENSYSSECRET }}/g' ./iniFile/config.ini

    - name: shuize run
      run: |
        cd ./ShuiZe_0x727
        sudo python ShuiZe.py -d sf.cn
        
    - name: save_result
      uses: actions/upload-artifact@v1
      with:
          name: result
          path: /home/runner/work/ShuiZeAciton/ShuiZeAciton/ShuiZe_0x727/result/
